import {
  australia,
  canada,
  hongKong,
  india,
  nigeria,
  uk,
  us,
} from "./flags";
import {
  NigelRichards,
  WellingtonJighere,
  DavidEldar,
  AlecSjoholm,
  KomolPanyasoponlert,
  PanupolSujjayakorn,
  ThachaKoowirat,
  TohWeibin,
  HubertWee,
  JakobTeitelbaum,
  MadhavKamath,
} from "./images";

// --- UPDATED RANKINGS DATA ---
// This data now matches the new table design
export const rankings = [
  {
    id: 1,
    rank: 1,
    name: "Nigel Richards",
    country: "New Zealand",
    countryFlag: "/flags/new-zealand.webp", // Example path
    rating: 2275,
    prevRating: 2260, // Added
    tournaments: 8, // Renamed from 'games' or 'totalPoints'
    change: 15, // Calculated from rating - prevRating
  },
  {
    id: 2,
    rank: 2,
    name: "Wellington Jighere",
    country: "Nigeria",
    countryFlag: nigeria,
    rating: 2230,
    prevRating: 2195, // Added
    tournaments: 5, // Renamed
    change: 35,
  },
  {
    id: 3,
    rank: 3,
    name: "David Eldar",
    country: "Australia",
    countryFlag: australia,
    rating: 2190,
    prevRating: 2192, // Added
    tournaments: 6, // Renamed
    change: -2,
  },
  {
    id: 4,
    rank: 4,
    name: "Adam Logan",
    country: "Canada",
    countryFlag: canada,
    rating: 2150,
    prevRating: 2150, // Added
    tournaments: 4, // Renamed
    change: 0,
  },
  {
    id: 5,
    rank: 5,
    name: "Lewis Mackay",
    country: "United Kingdom",
    countryFlag: uk,
    rating: 2145,
    prevRating: 2120, // Added
    tournaments: 7, // Renamed
    change: 25,
  },
  {
    id: 6,
    rank: 6,
    name: "Goutham Jayaraman",
    country: "India",
    countryFlag: india,
    rating: 2130,
    prevRating: 2135, // Added
    tournaments: 5, // Renamed
    change: -5,
  },
  {
    id: 7,
    rank: 7,
    name: "Will Anderson",
    country: "United States",
    countryFlag: us,
    rating: 2120,
    prevRating: 2100, // Added
    tournaments: 6, // Renamed
    change: 20,
  },
  {
    id: 8,
    rank: 8,
    name: "Cheah Siu Hean",
    country: "Hong Kong",
    countryFlag: hongKong,
    rating: 2110,
    prevRating: 2110, // Added
    tournaments: 3, // Renamed
    change: 0,
  },
];

export const topPlayers = [
  {
    id: 1,
    name: "Nigel Richards",
    country: "New Zealand",
    countryFlag: "/flags/new-zealand.webp",
    rating: 2275,
    image: NigelRichards,
  },
  {
    id: 2,
    name: "Wellington Jighere",
    country: "Nigeria",
    countryFlag: nigeria,
    rating: 2230,
    image: "/public/placeholder-user.jpg",
  },
  {
    id: 3,
    name: "David Eldar",
    country: "Australia",
    countryFlag: australia,
    rating: 2190,
    image: DavidEldar,
  },
  {
    id: 4,
    name: "Alec Sjoholm",
    country: "United States",
    countryFlag: us,
    rating: 2185,
    image: AlecSjoholm,
  },
  {
    id: 5,
    name: "Komol Panyasoponlert",
    country: "Thailand",
    countryFlag: "/flags/thailand.webp",
    rating: 2170,
    image: KomolPanyasoponlert,
  },
  {
    id: 6,
    name: "Panupol Sujjayakorn",
    country: "Thailand",
    countryFlag: "/flags/thailand.webp",
    rating: 2160,
    image: PanupolSujjayakorn,
  },
  {
    id: 7,
    name: "Thacha Koowirat",
    country: "Thailand",
    countryFlag: "/flags/thailand.webp",
    rating: 2155,
    image: ThachaKoowirat,
  },
  {
    id: 8,
    name: "Toh Weibin",
    country: "Singapore",
    countryFlag: "/flags/singapore.webp",
    rating: 2150,
    image: TohWeibin,
  },
  {
    id: 9,
    name: "Hubert Wee",
    country: "Singapore",
    countryFlag: "/flags/singapore.webp",
    rating: 2140,
    image: HubertWee,
  },
  {
    id: 10,
    name: "Jakob Teitelbaum",
    country: "United States",
    countryFlag: us,
    rating: 2130,
    image: JakobTeitelbaum,
  },
  {
    id: 11,
    name: "Madhav Kamath",
    country: "India",
    countryFlag: india,
    rating: 2120,
    image: MadhavKamath,
  },
];

export const events = [
  {
    startDate: "2025-01-12",
    endDate: "2025-01-14",
    continent: "African",
    country: "Nigeria",
    state: "Lagos",
    organizer: "SCAG",
  },
  {
    startDate: "2025-02-05",
    endDate: "2025-02-07",
    continent: "African",
    country: "Ghana",
    state: "Accra",
    organizer: "Game 1",
  },
  {
    startDate: "2025-03-10",
    endDate: "2025-03-13",
    continent: "American",
    country: "US",
    state: "Texas",
    organizer: "Game 2",
  },
  {
    startDate: "2025-04-20",
    endDate: "2025-04-22",
    continent: "European",
    country: "UK",
    state: "London",
    organizer: "Game 3",
  },
  {
    startDate: "2025-05-01",
    endDate: "2025-05-02",
    continent: "Asian",
    country: "Sri Lanka",
    state: "Colombo",
    organizer: "Game 4",
  },
  {
    startDate: "2025-05-10",
    endDate: "2025-05-12",
    continent: "African",
    country: "Nigeria",
    state: "Abuja",
    organizer: "SCAG",
  },
  {
    startDate: "2025-06-05",
    endDate: "2025-06-07",
    continent: "American",
    country: "US",
    state: "California",
    organizer: "Game 5",
  },
  {
    startDate: "2025-06-18",
    endDate: "2025-06-19",
    continent: "European",
    country: "UK",
    state: "Manchester",
    organizer: "Game 6",
  },
  {
    startDate: "2025-07-01",
    endDate: "2025-07-03",
    continent: "Asian",
    country: "Sri Lanka",
    state: "Kandy",
    organizer: "Game 7",
  },
  {
    startDate: "2025-07-14",
    endDate: "2025-07-16",
    continent: "African",
    country: "Ghana",
    state: "Kumasi",
    organizer: "SCAG",
  },
  {
    startDate: "2025-08-02",
    endDate: "2025-08-03",
    continent: "African",
    country: "Nigeria",
    state: "Enugu",
    organizer: "Game 8",
  },
  {
    startDate: "2in 2025-08-20",
    endDate: "2025-08-22",
    continent: "American",
    country: "US",
    state: "New York",
    organizer: "Game 9",
  },
  {
    startDate: "2025-09-10",
    endDate: "2025-09-12",
    continent: "European",
    country: "UK",
    state: "Birmingham",
    organizer: "SCAG",
  },
  {
    startDate: "2025-09-28",
    endDate: "2025-09-29",
    continent: "Asian",
    country: "Sri Lanka",
    state: "Galle",
    organizer: "Game 10",
  },
  {
    startDate: "2025-10-01",
    endDate: "2025-10-03",
    continent: "Online",
    country: "Online",
    state: "Virtual",
    organizer: "Game 11",
  },
  {
    startDate: "2025-10-14",
    endDate: "2025-10-15",
    continent: "African",
    country: "Ghana",
    state: "Tamale",
    organizer: "SCAG",
  },
  {
    startDate: "2025-10-22",
    endDate: "2025-10-24",
    continent: "American",
    country: "US",
    state: "Florida",
    organizer: "Game 12",
  },
  {
    startDate: "2025-11-03",
    endDate: "2025-11-04",
    continent: "European",
    country: "UK",
    state: "Liverpool",
    organizer: "Game 13",
  },
  {
    startDate: "2025-11-10",
    endDate: "2025-11-12",
    continent: "African",
    country: "Nigeria",
    state: "Kano",
    organizer: "SCAG",
  },
  {
    startDate: "2025-11-20",
    endDate: "2025-11-22",
    continent: "Online",
    country: "Online",
    state: "Virtual",
    organizer: "Game 14",
  },
  {
    startDate: "2025-12-01",
    endDate: "2025-12-03",
    continent: "Asian",
    country: "Sri Lanka",
    state: "Jaffna",
    organizer: "Game 15",
  },
  {
    startDate: "2025-12-10",
    endDate: "2025-12-12",
    continent: "African",
    country: "Ghana",
    state: "Cape Coast",
    organizer: "SCAG",
  },
  {
    startDate: "2026-01-05",
    endDate: "2026-01-07",
    continent: "American",
    country: "US",
    state: "Illinois",
    organizer: "Game 16",
  },
  {
    startDate: "2026-01-18",
    endDate: "2026-01-20",
    continent: "European",
    country: "UK",
    state: "Leeds",
    organizer: "Game 17",
  },
  {
    startDate: "2026-02-02",
    endDate: "2026-02-04",
    continent: "African",
    country: "Nigeria",
    state: "Port Harcourt",
    organizer: "SCAG",
  },
  {
    startDate: "2026-02-15",
    endDate: "2026-02-17",
    continent: "American",
    country: "US",
    state: "Washington",
    organizer: "Game 18",
  },
  {
    startDate: "2026-03-01",
    endDate: "2026-03-03",
    continent: "Asian",
    country: "Sri Lanka",
    state: "Matara",
    organizer: "Game 19",
  },
  {
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    continent: "African",
    country: "Ghana",
    state: "Sunyani",
    organizer: "Game 20",
  },
  {
    startDate: "2026-03-25",
    endDate: "2026-03-26",
    continent: "Online",
    country: "Online",
    state: "Virtual",
    organizer: "Game 21",
  },
  {
    startDate: "2026-04-02",
    endDate: "2026-04-04",
    continent: "African",
    country: "Nigeria",
    state: "Ibadan",
    organizer: "SCAG",
  },
];

export const news = [
  {
    id: 1,
    title: "WESPA Championship 2025 Announced",
    date: "2025-10-20",
    category: "Tournaments",
    image: "/images/scrabble_tournament.png",
    excerpt:
      "The WESPA Championship 2025 will be held in Las Vegas, USA. Dates and venue announced.",
  },
  {
    id: 2,
    title: "New Youth Program Launched",
    date: "2025-10-18",
    category: "Youth",
    image: "/images/young_people_playing.png",
    excerpt:
      "WESPA launches a new global youth program to promote Scrabble among young players.",
  },
  {
    id: 3,
    title: "Updated Rules Version 5.1 Released",
    date: "2025-10-15",
    category: "Rules",
    image: "/images/WESPA Rules-V5.1_8.jpg",
    excerpt:
      "WESPA releases version 5.1 of the official rules, effective from January 1, 2026.",
  },
  {
    id: 4,
    title: "Interview with Nigel Richards",
    date: "2025-10-12",
    category: "Players",
    image: NigelRichards,
    excerpt:
      "We sit down with Scrabble legend Nigel Richards to discuss his career and future plans.",
  },
  {
    id: 5,
    title: "Online Ratings System Update",
    date: "2025-10-10",
    category: "Ratings",
    image: "/images/people_playing.png",
    excerpt:
      "The WESPA online ratings system has been updated with new features and improvements.",
  },
  {
    id: 6,
    title: "WESPA Welcomes New Member Nations",
    date: "2025-10-08",
    category: "Members",
    image: "/images/world-map-scrabble.png",
    excerpt:
      "WESPA is proud to welcome three new member nations: Ghana, Nigeria, and Kenya.",
  },
];