import {
  australia,
  canada,
  hongKong,
  india,
  nigeria,
  uk,
  us,
} from "./flags";
import {
  NigelRichards,
  WellingtonJighere,
  DavidEldar,
  AlecSjoholm,
  KomolPanyasoponlert,
  PanupolSujjayakorn,
  ThachaKoowirat,
  TohWeibin,
  HubertWee,
  JakobTeitelbaum,
  MadhavKamath,
} from "./images";

// --- UPDATED RANKINGS DATA ---
// This data now matches the new table design
export const rankings = [
  {
    id: 1,
    rank: 1,
    name: "Nigel Richards",
    country: "New Zealand",
    countryFlag: "/flags/new-zealand.webp", // Example path
    rating: 2275,
    prevRating: 2260, // Added
    tournaments: 8, // Renamed from 'games' or 'totalPoints'
    change: 15, // Calculated from rating - prevRating
  },
  {
    id: 2,
    rank: 2,
    name: "Wellington Jighere",
    country: "Nigeria",
    countryFlag: nigeria,
    rating: 2230,
    prevRating: 2195, // Added
    tournaments: 5, // Renamed
    change: 35,
  },
  {
    id: 3,
    rank: 3,
    name: "David Eldar",
    country: "Australia",
    countryFlag: australia,
    rating: 2190,
    prevRating: 2192, // Added
    tournaments: 6, // Renamed
    change: -2,
  },
  {
    id: 4,
    rank: 4,
    name: "Adam Logan",
    country: "Canada",
    countryFlag: canada,
    rating: 2150,
    prevRating: 2150, // Added
    tournaments: 4, // Renamed
    change: 0,
  },
  {
    id: 5,
    rank: 5,
    name: "Lewis Mackay",
    country: "United Kingdom",
    countryFlag: uk,
    rating: 2145,
    prevRating: 2120, // Added
    tournaments: 7, // Renamed
    change: 25,
  },
  {
    id: 6,
    rank: 6,
    name: "Goutham Jayaraman",
    country: "India",
    countryFlag: india,
    rating: 2130,
    prevRating: 2135, // Added
    tournaments: 5, // Renamed
    change: -5,
  },
  {
    id: 7,
    rank: 7,
    name: "Will Anderson",
    country: "United States",
    countryFlag: us,
    rating: 2120,
    prevRating: 2100, // Added
    tournaments: 6, // Renamed
    change: 20,
  },
  {
    id: 8,
    rank: 8,
    name: "Cheah Siu Hean",
    country: "Hong Kong",
    countryFlag: hongKong,
    rating: 2110,
    prevRating: 2110, // Added
    tournaments: 3, // Renamed
    change: 0,
  },
];

export const topPlayers = [
  {
    id: 1,
    name: "Nigel Richards",
    country: "New Zealand",
    countryFlag: "/flags/new-zealand.webp",
    rating: 2275,
    image: NigelRichards,
  },
  {
    id: 2,
    name: "Wellington Jighere",
    country: "Nigeria",
    countryFlag: nigeria,
    rating: 2230,
    image: "/public/placeholder-user.jpg",
  },
  {
    id: 3,
    name: "David Eldar",
    country: "Australia",
    countryFlag: australia,
    rating: 2190,
    image: DavidEldar,
  },
  {
    id: 4,
    name: "Alec Sjoholm",
    country: "United States",
    countryFlag: us,
    rating: 2185,
    image: AlecSjoholm,
  },
  {
    id: 5,
    name: "Komol Panyasoponlert",
    country: "Thailand",
    countryFlag: "/flags/thailand.webp",
    rating: 2170,
    image: KomolPanyasoponlert,
  },
  {
    id: 6,
    name: "Panupol Sujjayakorn",
    country: "Thailand",
    countryFlag: "/flags/thailand.webp",
    rating: 2160,
    image: PanupolSujjayakorn,
  },
  {
    id: 7,
    name: "Thacha Koowirat",
    country: "Thailand",
    countryFlag: "/flags/thailand.webp",
    rating: 2155,
    image: ThachaKoowirat,
  },
  {
    id: 8,
    name: "Toh Weibin",
    country: "Singapore",
    countryFlag: "/flags/singapore.webp",
    rating: 2150,
    image: TohWeibin,
  },
  {
    id: 9,
    name: "Hubert Wee",
    country: "Singapore",
    countryFlag: "/flags/singapore.webp",
    rating: 2140,
    image: HubertWee,
  },
  {
    id: 10,
    name: "Jakob Teitelbaum",
    country: "United States",
    countryFlag: us,
    rating: 2130,
    image: JakobTeitelbaum,
  },
  {
    id: 11,
    name: "Madhav Kamath",
    country: "India",
    countryFlag: india,
    rating: 2120,
    image: MadhavKamath,
  },
];

export const events = [
  {
    id: 1,
    startDate: "2025-01-12",
    endDate: "2025-01-14",
    continent: "africa",
    country: "Nigeria",
    state: "Lagos",
    organizer: "SCAG",
    games: 8,
    eventName: "WESPA Africa Kickoff 2025 - Awolowo - Early Bird 🥇"
  },
  {
    id: 2,
    startDate: "2025-02-05",
    endDate: "2025-02-07",
    continent: "africa",
    country: "Ghana",
    state: "Accra",
    organizer: "Game 1",
    games: 6,
    eventName: "New Year Scrabble Clash - Akwaba - Early Bird 🎉"
  },
  {
    id: 3,
    startDate: "2025-03-10",
    endDate: "2025-03-13",
    continent: "america",
    country: "US",
    state: "Texas",
    organizer: "Game 2",
    games: 10,
    eventName: "Texas Open 2025 - Invictus Challenge ⭐"
  },
  {
    id: 4,
    startDate: "2025-04-20",
    endDate: "2025-04-22",
    continent: "europe",
    country: "UK",
    state: "London",
    organizer: "Game 3",
    games: 7,
    eventName: "WESPA European Masters"
  },
  {
    id: 5,
    startDate: "2025-05-01",
    endDate: "2025-05-02",
    continent: "asia",
    country: "Sri Lanka",
    state: "Colombo",
    organizer: "Game 4",
    games: 9,
    eventName: "Colombo Challenge 2025"
  },
  {
    id: 6,
    startDate: "2025-05-10",
    endDate: "2025-05-12",
    continent: "africa",
    country: "Nigeria",
    state: "Abuja",
    organizer: "SCAG",
    games: 6,
    eventName: "Abuja Invitational"
  },
  {
    id: 7,
    startDate: "2025-06-05",
    endDate: "2025-06-07",
    continent: "america",
    country: "US",
    state: "California",
    organizer: "Game 5",
    games: 8,
    eventName: "California Summer Open"
  },
  {
    id: 8,
    startDate: "2025-06-18",
    endDate: "2025-06-19",
    continent: "europe",
    country: "UK",
    state: "Manchester",
    organizer: "Game 6",
    games: 5,
    eventName: "Manchester Mind Games"
  },
  {
    id: 9,
    startDate: "2025-07-01",
    endDate: "2025-07-03",
    continent: "asia",
    country: "Sri Lanka",
    state: "Kandy",
    organizer: "Game 7",
    games: 7,
    eventName: "Kandy Invitational 2025"
  },
  {
    id: 10,
    startDate: "2025-07-14",
    endDate: "2025-07-16",
    continent: "africa",
    country: "Ghana",
    state: "Kumasi",
    organizer: "SCAG",
    games: 10,
    eventName: "Kumasi Scrabble Open"
  },
  {
    id: 11,
    startDate: "2025-08-02",
    endDate: "2025-08-03",
    continent: "africa",
    country: "Nigeria",
    state: "Enugu",
    organizer: "Game 8",
    games: 6,
    eventName: "Enugu Regional Games"
  },
  {
    id: 12,
    startDate: "2025-08-20",
    endDate: "2025-08-22",
    continent: "america",
    country: "US",
    state: "New York",
    organizer: "Game 9",
    games: 8,
    eventName: "New York Classic 2025"
  },
  {
    id: 13,
    startDate: "2025-09-10",
    endDate: "2025-09-12",
    continent: "europe",
    country: "UK",
    state: "Birmingham",
    organizer: "SCAG",
    games: 9,
    eventName: "WESPA European Cup 2025"
  },
  {
    id: 14,
    startDate: "2025-09-28",
    endDate: "2025-09-29",
    continent: "asia",
    country: "Sri Lanka",
    state: "Galle",
    organizer: "Game 10",
    games: 5,
    eventName: "Galle City Challenge"
  },
  {
    id: 15,
    startDate: "2025-10-01",
    endDate: "2025-10-03",
    continent: "online",
    country: "Online",
    state: "Virtual",
    organizer: "Game 11",
    games: 10,
    eventName: "Virtual Masters 2025"
  },
  {
    id: 16,
    startDate: "2025-10-14",
    endDate: "2025-10-15",
    continent: "africa",
    country: "Ghana",
    state: "Tamale",
    organizer: "SCAG",
    games: 8,
    eventName: "Tamale Invitational"
  },
  {
    id: 17,
    startDate: "2025-10-22",
    endDate: "2025-10-24",
    continent: "america",
    country: "US",
    state: "Florida",
    organizer: "Game 12",
    games: 6,
    eventName: "Florida Sunshine Cup"
  },
  {
    id: 18,
    startDate: "2025-11-03",
    endDate: "2025-11-04",
    continent: "europe",
    country: "UK",
    state: "Liverpool",
    organizer: "Game 13",
    games: 7,
    eventName: "Liverpool Scrabble Series"
  },
  {
    id: 19,
    startDate: "2025-11-10",
    endDate: "2025-11-12",
    continent: "africa",
    country: "Nigeria",
    state: "Kano",
    organizer: "SCAG",
    games: 9,
    eventName: "Kano Regional Cup"
  },
  {
    id: 20,
    startDate: "2025-11-20",
    endDate: "2025-11-22",
    continent: "online",
    country: "Online",
    state: "Virtual",
    organizer: "Game 14",
    games: 8,
    eventName: "Online Global Open"
  },
  {
    id: 21,
    startDate: "2025-12-01",
    endDate: "2025-12-03",
    continent: "asia",
    country: "Sri Lanka",
    state: "Jaffna",
    organizer: "Game 15",
    games: 7,
    eventName: "Jaffna Scrabble Masters"
  },
  {
    id: 22,
    startDate: "2025-12-10",
    endDate: "2025-12-12",
    continent: "africa",
    country: "Ghana",
    state: "Cape Coast",
    organizer: "SCAG",
    games: 10,
    eventName: "Cape Coast Championship"
  },
  {
    id: 23,
    startDate: "2026-01-05",
    endDate: "2026-01-07",
    continent: "america",
    country: "US",
    state: "Illinois",
    organizer: "Game 16",
    games: 5,
    eventName: "Winter Scrabble Festival"
  },
  {
    id: 24,
    startDate: "2026-01-18",
    endDate: "2026-01-20",
    continent: "europe",
    country: "UK",
    state: "Leeds",
    organizer: "Game 17",
    games: 10,
    eventName: "Leeds Masters 2026"
  },
  {
    id: 25,
    startDate: "2026-02-02",
    endDate: "2026-02-04",
    continent: "africa",
    country: "Nigeria",
    state: "Port Harcourt",
    organizer: "SCAG",
    games: 7,
    eventName: "Port Harcourt Invitational"
  },
  {
    id: 26,
    startDate: "2026-02-15",
    endDate: "2026-02-17",
    continent: "america",
    country: "US",
    state: "Washington",
    organizer: "Game 18",
    games: 6,
    eventName: "Capital Scrabble Classic"
  },
  {
    id: 27,
    startDate: "2026-03-01",
    endDate: "2026-03-03",
    continent: "asia",
    country: "Sri Lanka",
    state: "Matara",
    organizer: "Game 19",
    games: 8,
    eventName: "Matara Regional Cup"
  },
  {
    id: 28,
    startDate: "2026-03-10",
    endDate: "2026-03-12",
    continent: "africa",
    country: "Ghana",
    state: "Sunyani",
    organizer: "Game 20",
    games: 9,
    eventName: "Sunyani Challenge"
  },
  {
    id: 29,
    startDate: "2026-03-25",
    endDate: "2026-03-26",
    continent: "online",
    country: "Online",
    state: "Virtual",
    organizer: "Game 21",
    games: 10,
    eventName: "Virtual Spring Championship"
  },
  {
    id: 30,
    startDate: "2026-04-02",
    endDate: "2026-04-04",
    continent: "africa",
    country: "Nigeria",
    state: "Ibadan",
    organizer: "SCAG",
    games: 8,
    eventName: "Ibadan Scrabble Open"
  },
  // 🌏 Oceania Events
  {
    id: 31,
    startDate: "2025-04-10",
    endDate: "2025-04-12",
    continent: "oceania",
    country: "Australia",
    state: "Sydney",
    organizer: "WESPA",
    games: 9,
    eventName: "Sydney Open 2025"
  },
  {
    id: 32,
    startDate: "2025-06-22",
    endDate: "2025-06-24",
    continent: "oceania",
    country: "New Zealand",
    state: "Auckland",
    organizer: "NZ Scrabble Club",
    games: 7,
    eventName: "Auckland Challenge 2025"
  },
  {
    id: 33,
    startDate: "2025-12-20",
    endDate: "2025-12-22",
    continent: "oceania",
    country: "Australia",
    state: "Melbourne",
    organizer: "WESPA",
    games: 10,
    eventName: "WESPA Championship 2025"
  }
];

export const ratings = [
  {
    id: 1,
    rank: 1,
    player_name: "Nigel Richards",
    country: "New Zealand",
    rating: 2180,
    total_games: 4206,
    last_played: "2025-06-01",
    totalPoints: 15420,
    countryCode: "NZL",
    status: "Active",
    bio: "Nigel Richards is widely regarded as the greatest Scrabble player of all time, known for his extraordinary memorization skills and ability to play in multiple languages.",
    achievements: ["3x World Scrabble Champion", "5x US National Scrabble Champion"],
    profileImage: "/placeholders/nigel-richards.jpg",
    recentGames: [
      { opponent: "David Eldar", result: "Win", score: "450-380" },
      { opponent: "Jesse Day", result: "Win", score: "420-350" },
      { opponent: "Komol Panyasophonlert", result: "Win", score: "480-390" }
    ],
  },
  {
    id: 2,
    rank: 2,
    player_name: "David Eldar",
    country: "Australia",
    rating: 2173,
    total_games: 1637,
    last_played: "2025-06-01",
    totalPoints: 14230,
    countryCode: "AUS",
    status: "Active",
    bio: "David Eldar is an Australian Scrabble player, a former World Scrabble Champion, renowned for his aggressive playing style and deep vocabulary.",
    achievements: ["World Scrabble Champion 2017", "Australian National Champion"],
    profileImage: "/placeholders/david-eldar.jpg",
    recentGames: [
      { opponent: "Nigel Richards", result: "Loss", score: "380-450" },
      { opponent: "Jesse Day", result: "Win", score: "410-370" },
      { opponent: "Komol Panyasophonlert", result: "Win", score: "430-360" }
    ],
  },
  {
    id: 3,
    rank: 3,
    player_name: "Jesse Day",
    country: "United States",
    rating: 2137,
    total_games: 1889,
    last_played: "2025-06-01",
    totalPoints: 13890,
    countryCode: "USA",
    status: "Active",
    bio: "Jesse Day is a prominent American Scrabble player, consistently ranked among the top players in the world. Known for his tactical play and strong endgame.",
    achievements: ["North American Scrabble Champion", "Multiple US Open Titles"],
    profileImage: "/placeholders/jesse-day.jpg",
    recentGames: [
      { opponent: "Komol Panyasophonlert", result: "Win", score: "420-390" },
      { opponent: "Nigel Richards", result: "Loss", score: "350-420" },
      { opponent: "David Eldar", result: "Loss", score: "370-410" }
    ],
  },
  {
    id: 4,
    rank: 4,
    player_name: "Komol Panyasophonlert",
    country: "Thailand",
    rating: 2103,
    total_games: 189,
    last_played: "2025-06-01",
    totalPoints: 13450,
    countryCode: "THA",
    status: "Active",
    bio: "Komol Panyasophonlert is a Thai Scrabble sensation, a formidable opponent with an impressive record in international tournaments.",
    achievements: ["Thailand National Champion", "King's Cup Champion"],
    profileImage: "/placeholders/komol-panyasophonlert.jpg",
    recentGames: [
      { opponent: "Jesse Day", result: "Loss", score: "390-420" },
      { opponent: "Nigel Richards", result: "Loss", score: "390-480" },
      { opponent: "David Eldar", result: "Loss", score: "360-430" }
    ],
  },
  {
    id: 5,
    rank: 5,
    player_name: "Austin Shin",
    country: "United States",
    rating: 2077,
    total_games: 1252,
    last_played: "2025-06-01",
    totalPoints: 13120,
    countryCode: "USA",
    status: "Active",
    bio: "Austin Shin is a rising star in the American Scrabble scene, known for his tactical prowess and strategic gameplay. A consistent top finisher in national events.",
    achievements: ["Oregon State Champion", "Youngest Player to win a major US Tournament"],
    profileImage: "/placeholders/austin-shin.jpg",
    recentGames: [
      { opponent: "Nigel Richards", result: "Win", score: "410-370" },
      { opponent: "David Eldar", result: "Loss", score: "350-400" },
      { opponent: "Jesse Day", result: "Loss", score: "360-440" }
    ],
  },
  {
    id: 6,
    rank: 6,
    player_name: "Panupol Sujjayakorn",
    country: "Thailand",
    rating: 2075,
    total_games: 1015,
    last_played: "2025-06-01",
    status: "Active",
    bio: "Panupol Sujjayakorn is a Thai Scrabble world champion known for his sharp wordplay and lightning-fast gameplay.",
    achievements: ["World Scrabble Champion 2003", "King's Cup Winner"],
    profileImage: "/placeholders/panupol-sujjayakorn.jpg",
    recentGames: [
      { opponent: "Nigel Richards", result: "Loss", score: "370-420" },
      { opponent: "Komol Panyasophonlert", result: "Win", score: "420-390" },
    ],
  },
  {
    id: 7,
    rank: 7,
    player_name: "Madhav Gopal Kamath",
    country: "India",
    rating: 2068,
    total_games: 1083,
    last_played: "2025-06-01",
    status: "Active",
    bio: "Madhav Gopal Kamath is one of India's top-ranked Scrabble players, known for his consistency and balanced playstyle.",
    achievements: ["India National Champion", "WESPA Top 10"],
    profileImage: "/placeholders/madhav-gopal-kamath.jpg",
    recentGames: [
      { opponent: "Toh Weibin", result: "Win", score: "410-380" },
      { opponent: "Thacha Koowirat", result: "Loss", score: "370-400" },
    ],
  },
  {
    id: 8,
    rank: 8,
    player_name: "Toh Weibin",
    country: "Singapore",
    rating: 2061,
    total_games: 1268,
    last_played: "2025-06-01",
    status: "Active",
    bio: "Toh Weibin is a Singaporean Scrabble champion, celebrated for being one of the youngest national champions in Asia.",
    achievements: ["Singapore National Champion", "WESPA Top 5"],
    profileImage: "/placeholders/toh-weibin.jpg",
    recentGames: [
      { opponent: "Madhav Gopal Kamath", result: "Loss", score: "380-410" },
      { opponent: "Nigel Richards", result: "Win", score: "410-390" },
    ],
  },
  {
    id: 9,
    rank: 9,
    player_name: "Thacha Koowirat",
    country: "Thailand",
    rating: 2060,
    total_games: 2081,
    last_played: "2025-06-13",
    status: "Active",
    bio: "Thacha Koowirat is a Thai Scrabble expert known for his tactical mid-game strategy and mastery of obscure words.",
    achievements: ["King’s Cup Finalist", "Asia-Pacific Champion"],
    profileImage: "/placeholders/thacha-koowirat.jpg",
    recentGames: [
      { opponent: "Toh Weibin", result: "Win", score: "400-370" },
      { opponent: "Komol Panyasophonlert", result: "Loss", score: "360-410" },
    ],
  },
  {
    id: 10,
    rank: 10,
    player_name: "Jakob Teitelbaum",
    country: "United States",
    rating: 2059,
    total_games: 227,
    last_played: "2025-10-01",
    status: "Active",
    bio: "Jakob Teitelbaum is a young American Scrabble player rapidly rising in global rankings, known for his word recall and sharp strategy.",
    achievements: ["North American Open Winner"],
    profileImage: "/placeholders/jakob-teitelbaum.jpg",
    recentGames: [
      { opponent: "David Eldar", result: "Loss", score: "350-410" },
      { opponent: "Nigel Richards", result: "Loss", score: "370-430" },
    ],
  },
  {
    id: 11,
    rank: 11,
    player_name: "Wellington Jighere",
    country: "Nigeria",
    rating: 2055,
    total_games: 1580,
    last_played: "2025-06-05",
    status: "Active",
    bio: "Wellington Jighere is a Nigerian Scrabble world champion, known for his calm play and strategic brilliance.",
    achievements: ["World Scrabble Champion 2015", "African Champion"],
    profileImage: "/placeholders/wellington-jighere.jpg",
  },
  {
    id: 12,
    rank: 12,
    player_name: "Brett Smitheram",
    country: "United Kingdom",
    rating: 2053,
    total_games: 1440,
    last_played: "2025-06-05",
    status: "Active",
    bio: "Brett Smitheram is a UK Scrabble player, former World Champion and frequent top-10 finisher in international events.",
    achievements: ["World Scrabble Champion 2016"],
    profileImage: "/placeholders/brett-smitheram.jpg",
  },
  {
    id: 13,
    rank: 13,
    player_name: "Lewis Mackay",
    country: "United Kingdom",
    rating: 2045,
    total_games: 1522,
    last_played: "2025-06-05",
    status: "Active",
    bio: "Lewis Mackay is a consistent top UK player, known for his endgame precision and positional play.",
    achievements: ["UK National Champion", "World Runner-up 2015"],
    profileImage: "/placeholders/lewis-mackay.jpg",
  },
  {
    id: 14,
    rank: 14,
    player_name: "Pakorn Nemitrmansuk",
    country: "Thailand",
    rating: 2041,
    total_games: 1489,
    last_played: "2025-06-05",
    status: "Active",
    bio: "Pakorn Nemitrmansuk is a veteran Thai Scrabble champion known for consistency and elegant word mastery.",
    achievements: ["World Scrabble Champion 2009"],
    profileImage: "/placeholders/pakorn-nemitrmansuk.jpg",
  },
  {
    id: 15,
    rank: 15,
    player_name: "Jiaqi Woo",
    country: "Singapore",
    rating: 2037,
    total_games: 1382,
    last_played: "2025-06-05",
    status: "Active",
    bio: "Jiaqi Woo is one of Singapore's top female Scrabble players, known for her composure and technical mastery.",
    achievements: ["WESPA Female Champion", "Singapore Open Winner"],
    profileImage: "/placeholders/jiaqi-woo.jpg",
  },
  {
    id: 16,
    rank: 16,
    player_name: "Paul Gallen",
    country: "Australia",
    rating: 2029,
    total_games: 1280,
    last_played: "2025-07-01",
    status: "Active",
    bio: "Paul Gallen is a leading Australian player recognized for consistent international performances.",
    achievements: ["Australian Open Winner"],
    profileImage: "/placeholders/paul-gallen.jpg",
  },
  {
    id: 17,
    rank: 17,
    player_name: "Elize Plaatjies",
    country: "South Africa",
    rating: 2015,
    total_games: 1170,
    last_played: "2025-07-01",
    status: "Active",
    bio: "Elize Plaatjies is one of Africa's top Scrabble players, combining strategy and deep word study.",
    achievements: ["African Champion", "Top 10 WESPA Rankings"],
    profileImage: "/placeholders/elize-plaatjies.jpg",
  },
  {
    id: 18,
    rank: 18,
    player_name: "Jackson Smylie",
    country: "Canada",
    rating: 2007,
    total_games: 1120,
    last_played: "2025-07-15",
    status: "Active",
    bio: "Jackson Smylie is a Canadian Scrabble star and Twitch streamer, famous for bringing Scrabble to a new audience.",
    achievements: ["Canadian National Champion"],
    profileImage: "/placeholders/jackson-smylie.jpg",
  },
  {
    id: 19,
    rank: 19,
    player_name: "Sam Kantimathi",
    country: "United States",
    rating: 1999,
    total_games: 1043,
    last_played: "2025-07-15",
    status: "Active",
    bio: "Sam Kantimathi is a veteran US player and coach, active in the Scrabble education scene.",
    achievements: ["North American Championship Finalist"],
    profileImage: "/placeholders/sam-kantimathi.jpg",
  },
  {
    id: 20,
    rank: 20,
    player_name: "Marilyn Alberto",
    country: "Philippines",
    rating: 1990,
    total_games: 990,
    last_played: "2025-08-01",
    status: "Active",
    bio: "Marilyn Alberto is one of the leading Scrabble players in the Philippines, known for her dynamic play.",
    achievements: ["Philippine Open Champion"],
    profileImage: "/placeholders/marilyn-alberto.jpg",
  },
];

export const news = [
  {
    id: 1,
    title: "WESPA Championship 2025 Announced",
    date: "2025-10-20",
    category: "Tournaments",
    image: "/images/scrabble_tournament.png",
    excerpt:
      "The WESPA Championship 2025 will be held in Las Vegas, USA. Dates and venue announced.",
  },
  {
    id: 2,
    title: "New Youth Program Launched",
    date: "2025-10-18",
    category: "Youth",
    image: "/images/young_people_playing.png",
    excerpt:
      "WESPA launches a new global youth program to promote Scrabble among young players.",
  },
  {
    id: 3,
    title: "Updated Rules Version 5.1 Released",
    date: "2025-10-15",
    category: "Rules",
    image: "/images/WESPA Rules-V5.1_8.jpg",
    excerpt:
      "WESPA releases version 5.1 of the official rules, effective from January 1, 2026.",
  },
  {
    id: 4,
    title: "Interview with Nigel Richards",
    date: "2025-10-12",
    category: "Players",
    image: NigelRichards,
    excerpt:
      "We sit down with Scrabble legend Nigel Richards to discuss his career and future plans.",
  },
  {
    id: 5,
    title: "Online Ratings System Update",
    date: "2025-10-10",
    category: "Ratings",
    image: "/images/people_playing.png",
    excerpt:
      "The WESPA online ratings system has been updated with new features and improvements.",
  },
  {
    id: 6,
    title: "WESPA Welcomes New Member Nations",
    date: "2025-10-08",
    category: "Members",
    image: "/images/world-map-scrabble.png",
    excerpt:
      "WESPA is proud to welcome three new member nations: Ghana, Nigeria, and Kenya.",
  },
];